CC		= g++
CFLAGS		= -g -c -Wall
SOURCES		= client.cpp ClientSender.cpp ClientReceiver.cpp ThreadSafeFile.cpp ../tcpsockets/tcpstream.cpp ../threads/thread.cpp ../tcpsockets/tcpconnector.cpp
INCLUDES	= -I. -I../threads -I../tcpsockets
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= client

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)

