CC		= g++
CFLAGS		= -g -c -Wall
LDFLAGS		= 
SOURCES		= ClientSender.cpp client.cpp ../tcpsockets/tcpstream.cpp ../threads/thread.cpp ../tcpsockets/tcpconnector.cpp
INCLUDES	= -I. -I../threads -I../tcpsockets
OBJECTS		= $(SOURCES:.cpp=.o)
TARGET		= client

all: $(SOURCES) $(TARGET)

$(TARGET): $(OBJECTS) 
	$(CC) $(LDFLAGS) $(OBJECTS) -o $@

.cpp.o:
	$(CC) $(CFLAGS) $(INCLUDES) $< -o $@

clean:
	rm -rf $(OBJECTS) $(TARGET)

