all:
	make -f Makefile.client
	make -f Makefile.server

clean:
	make -f Makefile.client clean
	make -f Makefile.server clean	

clear_text:
	make -f Makefile.client clear_text
	make -f Makefile.server clear_text